### ISSUE TITLE
Finish extension

### ISSUE THREAD

**Issue by crislin2046** [dosyago/22120#7]
Need to handle sessions/tabs independently, rather than here we can attach to browser target and capture everything, so there's a little more plumbing. 

Also we can't write to disk so format will be different and stored in chrome.storage.sync

**Comment by crislin2046** [comment]
Not sure, but an extension may not be required. Does not seem important right now in any case

**Comment by jackmac92** [comment]
Without the chrome extension, I need to always use the 22120 browser instead of my default chrome right? I'd like to use this more, but that might be a pain.

Rather than storing the data in `chrome.storage.sync`, what about using a Native Host to communicate with an installed? https://developer.chrome.com/docs/extensions/mv2/messaging/#native-messaging

I've done a few side projects with chrome extensions so I may be able to help! (I'm familiar/comfortable thinking about how content_scripts and background scripts should work together, and I've setup Native messaging before)

**Comment by c9fe** [comment]
@jackmac92 No.
